name: "GitHub Profile Stats for README"
description: "Update GitHub README with various statistics."

inputs:
  GITHUB_TOKEN:
    description: "GitHub token with permissions to update the README"
    required: true
  TIMEZONE:
    description: "The timezone to use for statistics calculation"
    required: false
    default: "America/Winnipeg"
  FEATURES:
    description: |
      A comma-separated list of stats to include (with order).
    required: false
    default: "DAY_STATS,WEEK_STATS"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    TIMEZONE: ${{ inputs.TIMEZONE }}
  args:
    - ${{ inputs.FEATURES }}

branding:
  icon: "activity"
  color: "orange"
